import type { EnemyDefinition } from '../types/game';

export const ENEMY_DEFINITIONS: readonly EnemyDefinition[] = [
  {
    id: 'lol',
    name: '한글자',
    messages: ['긁', '왜', '흠', '또'],
    archetype: 'normal',
    color: 0xff5c72,
    radius: 20,
    maxHp: 16,
    moveSpeed: 120,
    contactDamage: 8,
    experienceValue: 1,
  },
  {
    id: 'okay',
    name: '두글자',
    messages: ['지긁', '재긁', '설마', '또요'],
    archetype: 'normal',
    color: 0xff7a59,
    radius: 21,
    maxHp: 24,
    moveSpeed: 108,
    contactDamage: 10,
    experienceValue: 2,
  },
  {
    id: 'wanderer',
    name: '배회하는 두글자',
    messages: ['딴짓', '산책', '구경', '빙빙'],
    archetype: 'wanderer',
    color: 0x57c7ff,
    radius: 22,
    maxHp: 28,
    moveSpeed: 90,
    contactDamage: 9,
    experienceValue: 2,
  },
  {
    id: 'five-minutes',
    name: '세글자',
    messages: ['아직도', '언제해', '빨리해', '무쉰사'],
    archetype: 'normal',
    color: 0xf08bc8,
    radius: 23,
    maxHp: 36,
    moveSpeed: 94,
    contactDamage: 12,
    experienceValue: 3,
  },
  {
    id: 'urgent-deploy',
    name: '네글자',
    messages: ['지긁재긁', '쉽잖아요', 'AI한테', '이것밖에'],
    archetype: 'charger',
    color: 0xff304f,
    radius: 24,
    maxHp: 52,
    moveSpeed: 76,
    contactDamage: 16,
    experienceValue: 4,
    chargeSpeed: 330,
    chargeTriggerDistance: 280,
    chargeDuration: 620,
    chargeCooldown: 2_300,
  },
  {
    id: 'two-hour-meeting',
    name: '다섯글자',
    messages: ['왜오래걸려', '언제끝나냐', '아답답하다', '차라리내가'],
    archetype: 'tank',
    color: 0x8f5bff,
    radius: 34,
    maxHp: 100,
    moveSpeed: 58,
    contactDamage: 20,
    experienceValue: 5,
  },
  {
    id: 'middle-manager',
    name: '1단계 보스',
    messages: ['전에 말씀드렸는데요.', '쉽잖아요?', '제가 그냥 할게요.'],
    archetype: 'tank',
    color: 0xffb13b,
    radius: 48,
    maxHp: 2_400,
    moveSpeed: 48,
    contactDamage: 28,
    experienceValue: 40,
    isBoss: true,
  },
  {
    id: 'senior-manager',
    name: '2단계 보스',
    messages: ['신입도 이 정도는 하던데.', '왜 이렇게 오래 걸렸어요?', '이거 AI한테 물어보면 바로 나오던데.'],
    archetype: 'tank',
    color: 0xff6f91,
    radius: 53,
    maxHp: 4_200,
    moveSpeed: 52,
    contactDamage: 32,
    experienceValue: 70,
    isBoss: true,
  },
  {
    id: 'final-boss',
    name: '최종 보스',
    messages: ['이것밖에 못해?', 'AI가 더 잘할 것 같은데?', '긁?'],
    archetype: 'tank',
    color: 0xff304f,
    radius: 58,
    maxHp: 6_000,
    moveSpeed: 55,
    contactDamage: 36,
    experienceValue: 100,
    isBoss: true,
  },
] as const;

export function getEnemyDefinition(id: string): EnemyDefinition {
  const definition = ENEMY_DEFINITIONS.find((enemy) => enemy.id === id);
  if (!definition) {
    throw new Error(`알 수 없는 적입니다: ${id}`);
  }
  return definition;
}
