import type { UpgradeDefinition } from '../types/game';

export const UPGRADES: readonly UpgradeDefinition[] = [
  {
    id: 'coffee',
    name: '커피',
    description: '발걸음이 가벼워집니다',
    maxLevel: 5,
    rarity: 'common',
    weight: 10,
    modifiers: [{ stat: 'moveSpeed', operation: 'add', value: 30 }],
  },
  {
    id: 'steel-mental',
    name: '강철 멘탈',
    description: '멘탈과 긁힘 저항을 강화합니다',
    maxLevel: 5,
    rarity: 'common',
    weight: 10,
    modifiers: [
      { stat: 'maxHp', operation: 'add', value: 20 },
      { stat: 'armor', operation: 'add', value: 1 },
    ],
  },
  {
    id: 'fact-bombing',
    name: '팩트 폭격',
    description: '한 발의 위력을 높입니다',
    maxLevel: 5,
    rarity: 'common',
    weight: 10,
    modifiers: [{ stat: 'attackDamage', operation: 'add', value: 5 }],
  },
  {
    id: 'rapid-reply',
    name: '칼답',
    description: '더 빠른 주기로 공격합니다',
    maxLevel: 5,
    rarity: 'common',
    weight: 9,
    modifiers: [{ stat: 'attackCooldown', operation: 'multiply', value: 0.82 }],
  },
  {
    id: 'free-shipping',
    name: '무료배송',
    description: '경험치를 더 멀리서 끌어옵니다',
    maxLevel: 5,
    rarity: 'common',
    weight: 10,
    modifiers: [{ stat: 'pickupRange', operation: 'add', value: 35 }],
  },
  {
    id: 'read-ignore',
    name: '읽씹',
    description: '모든 적의 이동을 늦춥니다',
    maxLevel: 5,
    rarity: 'rare',
    weight: 5,
    modifiers: [{ stat: 'enemySpeedMultiplier', operation: 'multiply', value: 0.92 }],
  },
  {
    id: 'mental-recovery',
    name: '멘탈 회복',
    description: '매초 멘탈을 회복합니다',
    maxLevel: 5,
    rarity: 'rare',
    weight: 5,
    modifiers: [{ stat: 'regeneration', operation: 'add', value: 1 }],
  },
  {
    id: 'continuous-reply',
    name: '연속 답장',
    description: '한 번에 더 많은 탄환을 발사합니다',
    maxLevel: 4,
    rarity: 'rare',
    weight: 4,
    modifiers: [{ stat: 'projectileCount', operation: 'add', value: 1 }],
  },
  {
    id: 'jigeul-jaegeul',
    name: '지긁재긁',
    description: '공격 전반을 크게 강화합니다',
    maxLevel: 3,
    rarity: 'legendary',
    weight: 1,
    modifiers: [
      { stat: 'attackRange', operation: 'add', value: 100 },
      { stat: 'attackDamage', operation: 'add', value: 8 },
      { stat: 'attackCooldown', operation: 'multiply', value: 0.85 },
    ],
  },
] as const;
