import type { UpgradeDefinition } from '../types/game';

// 모든 능력은 3단계가 최대다. 일반은 기초 빌드, 희귀는 공격 방향,
// 에픽은 전투 메커니즘, 전설은 플레이 규칙을 바꾸는 효과를 담당한다.
export const UPGRADES: readonly UpgradeDefinition[] = [
  // Common
  {
    id: 'coffee',
    name: '커피 수혈',
    description: '발걸음이 가벼워집니다',
    maxLevel: 3,
    rarity: 'common',
    weight: 1,
    modifiers: [{ stat: 'moveSpeed', operation: 'add', value: 24 }],
  },
  {
    id: 'steel-mental',
    name: '강철 멘탈',
    description: '최대 멘탈과 피해 감소율을 올립니다',
    maxLevel: 3,
    rarity: 'common',
    weight: 1,
    modifiers: [
      { stat: 'maxHp', operation: 'add', value: 16 },
      { stat: 'armor', operation: 'add', value: 1 },
    ],
  },
  {
    id: 'fact-bombing',
    name: '팩트 폭격',
    description: '한 발의 위력을 높입니다',
    maxLevel: 3,
    rarity: 'common',
    weight: 1,
    modifiers: [{ stat: 'attackDamage', operation: 'add', value: 4 }],
  },
  {
    id: 'rapid-reply',
    name: '칼답',
    description: '초당 발사 수가 증가합니다',
    maxLevel: 3,
    rarity: 'common',
    weight: 1,
    modifiers: [{ stat: 'attackCooldown', operation: 'multiply', value: 0.88 }],
  },
  {
    id: 'cc-all',
    name: '전체 참조',
    description: '탄환이 더 먼 곳까지 날아갑니다',
    maxLevel: 3,
    rarity: 'common',
    weight: 1,
    modifiers: [{ stat: 'attackRange', operation: 'add', value: 80 }],
  },
  {
    id: 'free-shipping',
    name: '무료 배송',
    description: '경험치를 더 멀리서 끌어옵니다',
    maxLevel: 3,
    rarity: 'common',
    weight: 1,
    modifiers: [{ stat: 'pickupRange', operation: 'add', value: 45 }],
  },
  {
    id: 'quick-post',
    name: '빠른 전송',
    description: '탄환 속도와 사거리를 함께 높입니다',
    maxLevel: 3,
    rarity: 'common',
    weight: 1,
    modifiers: [
      { stat: 'projectileSpeed', operation: 'add', value: 100 },
      { stat: 'attackRange', operation: 'add', value: 35 },
    ],
  },
  {
    id: 'deep-breath',
    name: '심호흡',
    description: '피격 1초 후 멘탈을 빠르게 회복합니다',
    maxLevel: 3,
    rarity: 'common',
    weight: 1,
    modifiers: [{ stat: 'regeneration', operation: 'add', value: 4 }],
    special: '회복 상한: 최대 멘탈의 초당 10%',
  },
  {
    id: 'steady-hand',
    name: '손떨림 보정',
    description: '조금 더 빠르고 강한 탄환을 만듭니다',
    maxLevel: 3,
    rarity: 'common',
    weight: 1,
    modifiers: [
      { stat: 'attackDamage', operation: 'add', value: 2 },
      { stat: 'projectileSpeed', operation: 'add', value: 70 },
    ],
  },

  // Rare
  {
    id: 'read-ignore',
    name: '읽씹',
    description: '모든 적의 이동을 늦춥니다',
    maxLevel: 3,
    rarity: 'rare',
    weight: 1,
    modifiers: [{ stat: 'enemySpeedMultiplier', operation: 'multiply', value: 0.92 }],
  },
  {
    id: 'continuous-reply',
    name: '연속 답장',
    description: '한 번에 탄환을 하나 더 발사합니다',
    maxLevel: 3,
    rarity: 'rare',
    weight: 1,
    modifiers: [{ stat: 'projectileCount', operation: 'add', value: 1 }],
  },
  {
    id: 'overclock',
    name: '마감 임박',
    description: '강하고 빠르게 몰아칩니다',
    maxLevel: 3,
    rarity: 'rare',
    weight: 1,
    modifiers: [
      { stat: 'attackDamage', operation: 'add', value: 4 },
      { stat: 'attackCooldown', operation: 'multiply', value: 0.92 },
    ],
  },
  {
    id: 'wide-network',
    name: '인맥 확장',
    description: '전투와 경험치 획득 범위를 넓힙니다',
    maxLevel: 3,
    rarity: 'rare',
    weight: 1,
    modifiers: [
      { stat: 'attackRange', operation: 'add', value: 90 },
      { stat: 'pickupRange', operation: 'add', value: 55 },
    ],
  },
  {
    id: 'piercing-comment',
    name: '뼈 때리는 댓글',
    description: '탄환이 적을 뚫고 다음 적까지 공격합니다',
    maxLevel: 3,
    rarity: 'rare',
    weight: 1,
    effects: [{ key: 'pierce', value: 1 }],
    special: '관통 횟수 +1',
  },
  {
    id: 'fact-check',
    name: '팩트 체크',
    description: '확률적으로 강력한 치명타를 냅니다',
    maxLevel: 3,
    rarity: 'rare',
    weight: 1,
    effects: [
      { key: 'criticalChance', value: 0.08 },
      { key: 'criticalMultiplier', value: 0.25 },
    ],
    special: '치명타 확률 +8% · 위력 +25%',
  },
  {
    id: 'backtalk',
    name: '뒤에서 한마디',
    description: '공격할 때 등 뒤로도 탄환을 발사합니다',
    maxLevel: 3,
    rarity: 'rare',
    weight: 1,
    effects: [{ key: 'rearShot', value: 1 }],
    special: '후방 탄환 +1',
  },
  {
    id: 'emergency-snack',
    name: '비상 간식',
    description: '적을 처치할 때마다 멘탈을 조금 회복합니다',
    maxLevel: 3,
    rarity: 'rare',
    weight: 1,
    effects: [{ key: 'onKillHeal', value: 0.7 }],
    special: '처치 회복 +0.7',
  },

  // Epic
  {
    id: 'viral-post',
    name: '바이럴',
    description: '좌우로 퍼지는 추가 탄환을 발사합니다',
    maxLevel: 3,
    rarity: 'epic',
    weight: 1,
    effects: [{ key: 'sideShot', value: 1 }],
    modifiers: [{ stat: 'attackRange', operation: 'add', value: 100 }],
    special: '좌우 탄환 한 쌍 추가',
  },
  {
    id: 'flow-state',
    name: '몰입 상태',
    description: '움직임과 공격 리듬이 크게 빨라집니다',
    maxLevel: 3,
    rarity: 'epic',
    weight: 1,
    modifiers: [
      { stat: 'moveSpeed', operation: 'add', value: 38 },
      { stat: 'attackCooldown', operation: 'multiply', value: 0.84 },
    ],
  },
  {
    id: 'safe-zone',
    name: '완벽한 거리두기',
    description: '적은 느려지고 나는 더 단단해집니다',
    maxLevel: 3,
    rarity: 'epic',
    weight: 1,
    modifiers: [
      { stat: 'enemySpeedMultiplier', operation: 'multiply', value: 0.9 },
      { stat: 'armor', operation: 'add', value: 2 },
      { stat: 'maxHp', operation: 'add', value: 18 },
    ],
  },
  {
    id: 'screenshot',
    name: '박제',
    description: '처치한 적이 폭발해 주변 적을 공격합니다',
    maxLevel: 3,
    rarity: 'epic',
    weight: 1,
    effects: [
      { key: 'explosionRadius', value: 22 },
      { key: 'explosionDamage', value: 6 },
    ],
    special: '처치 폭발 범위·피해 증가',
  },
  {
    id: 'chain-email',
    name: '메일 돌려막기',
    description: '명중한 팩트가 가까운 적에게 연쇄됩니다',
    maxLevel: 3,
    rarity: 'epic',
    weight: 1,
    effects: [
      { key: 'chainTargets', value: 1 },
      { key: 'chainDamage', value: 5 },
    ],
    special: '연쇄 대상 +1 · 연쇄 피해 +5',
  },
  {
    id: 'deadline-nova',
    name: '회의 종료',
    description: '주기적으로 전방위 탄환을 뿜어냅니다',
    maxLevel: 3,
    rarity: 'epic',
    weight: 1,
    effects: [{ key: 'nova', value: 1 }],
    special: '광역 발동 주기·탄환 수 강화',
  },
  {
    id: 'cut-line',
    name: '말 끊기',
    description: '체력이 낮은 일반 적을 즉시 정리합니다',
    maxLevel: 3,
    rarity: 'epic',
    weight: 1,
    effects: [{ key: 'executeThreshold', value: 0.07 }],
    special: '일반 적 처형 기준 +7%',
  },
  {
    id: 'ghosting',
    name: '잠수 모드',
    description: '일정 시간마다 다음 피해를 완전히 무시합니다',
    maxLevel: 3,
    rarity: 'epic',
    weight: 1,
    effects: [{ key: 'shield', value: 1 }],
    special: '자동 보호막 재충전 단축',
  },

  // Legendary
  {
    id: 'jigeul-jaegeul',
    name: '지긁재긁',
    description: '모든 팩트가 빠르고 강한 치명타 후보가 됩니다',
    maxLevel: 3,
    rarity: 'legendary',
    weight: 1,
    modifiers: [
      { stat: 'attackDamage', operation: 'add', value: 10 },
      { stat: 'attackCooldown', operation: 'multiply', value: 0.8 },
    ],
    effects: [
      { key: 'criticalChance', value: 0.12 },
      { key: 'criticalMultiplier', value: 0.35 },
    ],
    special: '치명타 확률 +12% · 위력 +35%',
  },
  {
    id: 'main-character',
    name: '주인공 보정',
    description: '쓰러져도 한 번 되살아나 전투를 이어갑니다',
    maxLevel: 3,
    rarity: 'legendary',
    weight: 1,
    modifiers: [
      { stat: 'maxHp', operation: 'add', value: 25 },
      { stat: 'armor', operation: 'add', value: 2 },
    ],
    effects: [{ key: 'revive', value: 1 }],
    special: '부활 횟수 +1',
  },
  {
    id: 'infinite-thread',
    name: '무한 스레드',
    description: '탄환이 늘어나고 일정 확률로 공격이 복제됩니다',
    maxLevel: 3,
    rarity: 'legendary',
    weight: 1,
    modifiers: [{ stat: 'projectileCount', operation: 'add', value: 1 }],
    effects: [{ key: 'echoShotChance', value: 0.14 }],
    special: '공격 복제 확률 +14%',
  },
  {
    id: 'all-hands',
    name: '전사 메일',
    description: '앞·뒤·좌·우를 동시에 탄환으로 채웁니다',
    maxLevel: 3,
    rarity: 'legendary',
    weight: 1,
    effects: [
      { key: 'rearShot', value: 1 },
      { key: 'sideShot', value: 1 },
    ],
    modifiers: [{ stat: 'attackDamage', operation: 'add', value: 5 }],
    special: '후방 탄환 +1 · 좌우 탄환 한 쌍 추가',
  },
  {
    id: 'viral-legend',
    name: '전 국민 박제',
    description: '처치 폭발이 거대해지고 연쇄 폭발을 일으킵니다',
    maxLevel: 3,
    rarity: 'legendary',
    weight: 1,
    effects: [
      { key: 'explosionRadius', value: 45 },
      { key: 'explosionDamage', value: 12 },
      { key: 'projectileScale', value: 0.12 },
    ],
    special: '폭발 범위·피해·탄환 크기 대폭 증가',
  },
  {
    id: 'algorithm-pick',
    name: '알고리즘의 선택',
    description: '연쇄 공격이 더 멀리, 더 많이 번집니다',
    maxLevel: 3,
    rarity: 'legendary',
    weight: 1,
    effects: [
      { key: 'chainTargets', value: 2 },
      { key: 'chainDamage', value: 9 },
      { key: 'pierce', value: 1 },
    ],
    special: '연쇄 +2 · 연쇄 피해 +9 · 관통 +1',
  },
  {
    id: 'no-context',
    name: '맥락 삭제',
    description: '보스에게 강하고 약해진 일반 적을 즉시 지웁니다',
    maxLevel: 3,
    rarity: 'legendary',
    weight: 1,
    effects: [
      { key: 'bossDamage', value: 0.22 },
      { key: 'executeThreshold', value: 0.06 },
    ],
    special: '보스 피해 +22% · 일반 적 처형 +6%',
  },
  {
    id: 'counter-post',
    name: '역박제',
    description: '피격 순간 주변 적에게 피해를 되돌려줍니다',
    maxLevel: 3,
    rarity: 'legendary',
    weight: 1,
    effects: [
      { key: 'retaliationDamage', value: 14 },
      { key: 'shield', value: 1 },
    ],
    special: '피격 반격 +14 · 보호막 재충전 단축',
  },
] as const;
