import type { UpgradeDefinition } from '../types/game';

// 모든 능력은 3단계가 최대 레벨이다. 등급 확률은 UpgradeSystem에서
// 일반 68%, 희귀 22%, 에픽 8%, 전설 2%의 기본 가중치로 관리한다.
export const UPGRADES: readonly UpgradeDefinition[] = [
  {
    id: 'coffee',
    name: '커피 수혈',
    description: '발걸음이 가벼워집니다',
    maxLevel: 3,
    rarity: 'common',
    weight: 1,
    modifiers: [{ stat: 'moveSpeed', operation: 'add', value: 24 }],
  },
  {
    id: 'steel-mental',
    name: '강철 멘탈',
    description: '최대 멘탈과 방어력을 올립니다',
    maxLevel: 3,
    rarity: 'common',
    weight: 1,
    modifiers: [
      { stat: 'maxHp', operation: 'add', value: 18 },
      { stat: 'armor', operation: 'add', value: 1 },
    ],
  },
  {
    id: 'fact-bombing',
    name: '팩트 폭격',
    description: '한 발의 위력을 높입니다',
    maxLevel: 3,
    rarity: 'common',
    weight: 1,
    modifiers: [{ stat: 'attackDamage', operation: 'add', value: 5 }],
  },
  {
    id: 'rapid-reply',
    name: '칼답',
    description: '더 빠른 주기로 공격합니다',
    maxLevel: 3,
    rarity: 'common',
    weight: 1,
    modifiers: [{ stat: 'attackCooldown', operation: 'multiply', value: 0.88 }],
  },
  {
    id: 'cc-all',
    name: '전체 참조',
    description: '탄환이 더 먼 곳까지 날아갑니다',
    maxLevel: 3,
    rarity: 'common',
    weight: 1,
    modifiers: [{ stat: 'attackRange', operation: 'add', value: 85 }],
  },
  {
    id: 'free-shipping',
    name: '무료 배송',
    description: '경험치를 더 멀리서 끌어옵니다',
    maxLevel: 3,
    rarity: 'common',
    weight: 1,
    modifiers: [{ stat: 'pickupRange', operation: 'add', value: 45 }],
  },
  {
    id: 'quick-post',
    name: '빠른 전송',
    description: '탄환이 더 빠르게 날아갑니다',
    maxLevel: 3,
    rarity: 'common',
    weight: 1,
    modifiers: [{ stat: 'projectileSpeed', operation: 'add', value: 120 }],
  },
  {
    id: 'deep-breath',
    name: '심호흡',
    description: '조금씩 멘탈을 회복합니다',
    maxLevel: 3,
    rarity: 'common',
    weight: 1,
    modifiers: [{ stat: 'regeneration', operation: 'add', value: 0.5 }],
  },
  {
    id: 'read-ignore',
    name: '읽씹',
    description: '모든 적의 이동을 늦춥니다',
    maxLevel: 3,
    rarity: 'rare',
    weight: 1,
    modifiers: [{ stat: 'enemySpeedMultiplier', operation: 'multiply', value: 0.9 }],
  },
  {
    id: 'mental-recovery',
    name: '멘탈 회복',
    description: '회복력과 최대 멘탈을 함께 높입니다',
    maxLevel: 3,
    rarity: 'rare',
    weight: 1,
    modifiers: [
      { stat: 'regeneration', operation: 'add', value: 1.2 },
      { stat: 'maxHp', operation: 'add', value: 12 },
    ],
  },
  {
    id: 'continuous-reply',
    name: '연속 답장',
    description: '한 번에 탄환을 하나 더 발사합니다',
    maxLevel: 3,
    rarity: 'rare',
    weight: 1,
    modifiers: [{ stat: 'projectileCount', operation: 'add', value: 1 }],
  },
  {
    id: 'overclock',
    name: '마감 임박',
    description: '공격력과 공격 속도를 함께 높입니다',
    maxLevel: 3,
    rarity: 'rare',
    weight: 1,
    modifiers: [
      { stat: 'attackDamage', operation: 'add', value: 5 },
      { stat: 'attackCooldown', operation: 'multiply', value: 0.92 },
    ],
  },
  {
    id: 'wide-network',
    name: '인맥 확장',
    description: '공격과 획득 범위를 크게 넓힙니다',
    maxLevel: 3,
    rarity: 'rare',
    weight: 1,
    modifiers: [
      { stat: 'attackRange', operation: 'add', value: 100 },
      { stat: 'pickupRange', operation: 'add', value: 55 },
    ],
  },
  {
    id: 'viral-post',
    name: '바이럴',
    description: '더 많은 탄환을 더 멀리 퍼뜨립니다',
    maxLevel: 3,
    rarity: 'epic',
    weight: 1,
    modifiers: [
      { stat: 'projectileCount', operation: 'add', value: 1 },
      { stat: 'attackRange', operation: 'add', value: 150 },
      { stat: 'projectileSpeed', operation: 'add', value: 100 },
    ],
  },
  {
    id: 'flow-state',
    name: '몰입 상태',
    description: '움직임과 공격이 눈에 띄게 빨라집니다',
    maxLevel: 3,
    rarity: 'epic',
    weight: 1,
    modifiers: [
      { stat: 'moveSpeed', operation: 'add', value: 45 },
      { stat: 'attackCooldown', operation: 'multiply', value: 0.82 },
    ],
  },
  {
    id: 'safe-zone',
    name: '완벽한 거리두기',
    description: '적은 느려지고 나는 더 단단해집니다',
    maxLevel: 3,
    rarity: 'epic',
    weight: 1,
    modifiers: [
      { stat: 'enemySpeedMultiplier', operation: 'multiply', value: 0.88 },
      { stat: 'armor', operation: 'add', value: 2 },
      { stat: 'maxHp', operation: 'add', value: 20 },
    ],
  },
  {
    id: 'jigeul-jaegeul',
    name: '지긁재긁',
    description: '공격 전반이 폭발적으로 강해집니다',
    maxLevel: 3,
    rarity: 'legendary',
    weight: 1,
    modifiers: [
      { stat: 'attackRange', operation: 'add', value: 180 },
      { stat: 'attackDamage', operation: 'add', value: 12 },
      { stat: 'attackCooldown', operation: 'multiply', value: 0.78 },
    ],
  },
  {
    id: 'main-character',
    name: '주인공 보정',
    description: '공수 양면에서 빈틈없는 힘을 얻습니다',
    maxLevel: 3,
    rarity: 'legendary',
    weight: 1,
    modifiers: [
      { stat: 'maxHp', operation: 'add', value: 35 },
      { stat: 'armor', operation: 'add', value: 3 },
      { stat: 'regeneration', operation: 'add', value: 2 },
      { stat: 'attackDamage', operation: 'add', value: 10 },
    ],
  },
  {
    id: 'infinite-thread',
    name: '무한 스레드',
    description: '화면을 탄환으로 뒤덮는 전설의 연타입니다',
    maxLevel: 3,
    rarity: 'legendary',
    weight: 1,
    modifiers: [
      { stat: 'projectileCount', operation: 'add', value: 2 },
      { stat: 'attackCooldown', operation: 'multiply', value: 0.82 },
      { stat: 'projectileSpeed', operation: 'add', value: 180 },
    ],
  },
] as const;
