import type { WaveConfig } from '../types/game';

export const WAVES: readonly WaveConfig[] = [
  {
    id: 'warm-up',
    name: '평온한 척',
    startTime: 0,
    spawnInterval: 900,
    spawnCount: 1,
    maxEnemies: 35,
    enemyHpMultiplier: 1,
    enemySpeedMultiplier: 1,
    enemies: [
      { enemyId: 'lol', weight: 8 },
      { enemyId: 'okay', weight: 2 },
    ],
  },
  {
    id: 'notifications',
    name: '알림 폭주',
    startTime: 60,
    spawnInterval: 680,
    spawnCount: 1,
    maxEnemies: 50,
    enemyHpMultiplier: 1.2,
    enemySpeedMultiplier: 1.05,
    enemies: [
      { enemyId: 'lol', weight: 5 },
      { enemyId: 'okay', weight: 3 },
      { enemyId: 'five-minutes', weight: 2 },
    ],
  },
  {
    id: 'release-hour',
    name: '배포 시간',
    startTime: 120,
    spawnInterval: 540,
    spawnCount: 1,
    maxEnemies: 65,
    enemyHpMultiplier: 1.45,
    enemySpeedMultiplier: 1.1,
    enemies: [
      { enemyId: 'lol', weight: 4 },
      { enemyId: 'okay', weight: 3 },
      { enemyId: 'five-minutes', weight: 2 },
      { enemyId: 'urgent-deploy', weight: 2 },
    ],
  },
  {
    id: 'endless-meeting',
    name: '끝없는 회의',
    startTime: 180,
    spawnInterval: 460,
    spawnCount: 2,
    maxEnemies: 80,
    enemyHpMultiplier: 1.8,
    enemySpeedMultiplier: 1.15,
    enemies: [
      { enemyId: 'lol', weight: 3 },
      { enemyId: 'okay', weight: 2 },
      { enemyId: 'five-minutes', weight: 3 },
      { enemyId: 'urgent-deploy', weight: 3 },
      { enemyId: 'two-hour-meeting', weight: 2 },
    ],
  },
  {
    id: 'mental-breakdown',
    name: '멘탈 비상',
    startTime: 240,
    spawnInterval: 380,
    spawnCount: 2,
    maxEnemies: 95,
    enemyHpMultiplier: 2.25,
    enemySpeedMultiplier: 1.2,
    enemies: [
      { enemyId: 'lol', weight: 2 },
      { enemyId: 'okay', weight: 2 },
      { enemyId: 'five-minutes', weight: 3 },
      { enemyId: 'urgent-deploy', weight: 4 },
      { enemyId: 'two-hour-meeting', weight: 3 },
    ],
  },
] as const;
